var annotated =
[
    [ "ArrayOfMessageRecipientOfInt32", "class_array_of_message_recipient_of_int32.html", "class_array_of_message_recipient_of_int32" ],
    [ "CSV", "class_c_s_v.html", "class_c_s_v" ],
    [ "DB", "class_d_b.html", "class_d_b" ],
    [ "DbGrid", "class_db_grid.html", "class_db_grid" ],
    [ "Debug", "class_debug.html", "class_debug" ],
    [ "DeleteCallsRequest", "class_delete_calls_request.html", "class_delete_calls_request" ],
    [ "Filter", "class_filter.html", "class_filter" ],
    [ "FSDB", "class_f_s_d_b.html", "class_f_s_d_b" ],
    [ "FSTable", "class_f_s_table.html", "class_f_s_table" ],
    [ "GetCallsRequest", "class_get_calls_request.html", "class_get_calls_request" ],
    [ "GetCampaignStatsRequest", "class_get_campaign_stats_request.html", "class_get_campaign_stats_request" ],
    [ "Hook", "class_hook.html", "class_hook" ],
    [ "IP2CO", "class_i_p2_c_o.html", "class_i_p2_c_o" ],
    [ "LoginRequest", "class_login_request.html", "class_login_request" ],
    [ "Mailer", "class_mailer.html", "class_mailer" ],
    [ "MessageRecipientOfInt32", "class_message_recipient_of_int32.html", "class_message_recipient_of_int32" ],
    [ "MobiDetect", "class_mobi_detect.html", "class_mobi_detect" ],
    [ "Navigation", "class_navigation.html", "class_navigation" ],
    [ "Record", "class_record.html", "class_record" ],
    [ "Request", "class_request.html", "class_request" ],
    [ "RoboTalker", "class_robo_talker.html", "class_robo_talker" ],
    [ "ScheduleCallsRequestOfInt32", "class_schedule_calls_request_of_int32.html", "class_schedule_calls_request_of_int32" ],
    [ "Template", "class_template.html", "class_template" ]
];